version: '3'
services:
  mariadb:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_USER: master
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: user_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
    ports:
      - 6379:6379