spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 30000
      minimum-idle: 100
      maximum-pool-size: 100
  data:
    redis:
      host: localhost
      port: 6379